### ISSUE TITLE
qbittorrent-nox

### ISSUE THREAD

**Issue by th0masfrancis** [qBitMF/qBitMF#12]
start.sh tries to start qbittorent-nox but qbittorent-nox is not installed as part of the docker build
I was able to start the qbittorent UI only after manually installing qbittorent-nox in the docker. Still I was unable to start any downloads.

start.sh gives the following error - 2023/03/24 13:19:34 socat[172] E bind(5, {AF=2 0.0.0.0:8080}, 16): Address already in use

**Comment by vishal-repaka** [comment]
Hey @th0masfrancis - how were you able to resolve this? I am getting the same issue when running the docker container

`2023-04-06 01:32:30 qbitmf  | /start-unpriv.sh: line 14: qbittorrent-nox: command not found`
