### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by Dulanic** [qBitMF/qBitMF#2]
When I try to build, it has a bunch of errors, and I am unable to connect at all. The container log doesn't say much. I currently use separate wireguard and QBT containers, so this project interested me for sure.

```
usermod: no changes
Configuring interface '1'
Configuring interface '2'
Configuring interface '3'
```

Here is my build log.
[build.log](https://github.com/qBitMF/qBitMF/files/9364731/build.log)

**Comment by k3d3** [comment]
Change your interface config file names. Instead of writing them `1.conf`, `2.conf`, and `3.conf`, name them `wg1.conf`, `wg2.conf`, and `wg3.conf`.

This happens because of my laziness when writing the python script that parses wireguard configs. It just sets the interface name to whatever the filename is, and breaks if the filename isn't a valid interface name (as is the case with just a straight-up number).

**Comment by Dulanic** [comment]
So is the build errors expected and I just need to change the conf? or do I need to rebuild?

**Comment by k3d3** [comment]
You shouldn't need to rebuild the image - from the looks of your build.log, the image building actually succeeded. You should only need to restart the container (or if that fails, destroy the container and recreate it).

**Comment by Dulanic** [comment]
Same issue, the build does succedd, but there is a bunch of errors during it. Same log and no connectivity.

```usermod: no changes
Configuring interface 'wg1'
Configuring interface 'wg2'
Configuring interface 'wg3'
```

[build.log](https://github.com/qBitMF/qBitMF/files/9365094/build.log)

**Comment by k3d3** [comment]
Those build messages are just warnings, and they exist while building qBittorrent itself. Those warning messages exist in the original qBittorrent build process as well.

I don't have any specific steps for how to fix it, but I can give some suggestions.

Firstly, if you run `docker-compose exec qbitmf wgbash`, it'll drop you into a shell within the wireguard network namespace, which means you'll have the same access qBittorrent does. From there, you can try pinging things, using netcat, monitoring with tcpdump or vnstat, etc.

Hopefully that helps.

**Comment by k3d3** [comment]
It might also be worthwhile to look at the qBittorrent log files in your config directory.

**Comment by Dulanic** [comment]
I got it, guess you have to had ports set in QBT or it fails to connect at all. Thanks for your help!
